In [1]:
import pandas as pd
import numpy as np
from fredapi import Fred
fred = Fred(api_key="2bc6a527e0a892d7b9862b9a43034900")

def print_shape(thing):
    print(thing)
    print(thing.shape)

def head_shape(thing):
    thing.head()
    print(thing.shape)

def tail_shape(thing):
    thing.tail()
    print(thing.shape)

In [2]:
ampi = pd.read_csv(r"C:\Users\varia\OneDrive\Dragon Hoard's Index\Datasets\Art-Market-Performance-Indexes-to-Jan-2026.csv")
ampi = ampi.drop(columns = ['Date.1', 'AMPC UMV', 'Index (1000 in 1978).1', 'Smoothed Index (0.2 alpha).1'])
ampi.head()

     Date  AMPI UMV  Index (1000 in 1978)  Smoothed Index (0.2 alpha)
0  Dec-77   9758162              0.000000                    0.000000
1  Jan-78   9981595           1000.000000                    0.000000
2  Feb-78   9915160            993.344250                  200.000000
3  Mar-78  10055701           1007.424264                  358.668850
4  Apr-78   9859396            987.757568                  488.419933

In [3]:
gbp_usd = fred.get_series("EXUSUK", observation_start = "1977-12-01", frequency = "m")

In [4]:
r, c = np.where(ampi == "01-Jan")
print(r)
print(c)
print(ampi.iat[277, 0])

[277]
[0]
01-Jan

In [5]:
ampi1 = ampi[:277].copy()
ampi2 = ampi[277:].copy()

In [6]:
ampi1['Date'] = pd.to_datetime(ampi1['Date'], format = '%b-%y')
ampi2['Date'] = pd.to_datetime(ampi2['Date'], format = '%y-%b')

In [7]:
df = pd.concat([ampi1, ampi2])

In [8]:
gbp_usd.head()

1977-12-01    1.8546
1978-01-01    1.9353
1978-02-01    1.9396
1978-03-01    1.9055
1978-04-01    1.8497
dtype: float64

In [9]:
ampi_fixed = df.set_index('Date')

In [10]:
ampi_fixed.head()

            AMPI UMV  Index (1000 in 1978)  Smoothed Index (0.2 alpha)
Date
1977-12-01   9758162              0.000000                    0.000000
1978-01-01   9981595           1000.000000                    0.000000
1978-02-01   9915160            993.344250                  200.000000
1978-03-01  10055701           1007.424264                  358.668850
1978-04-01   9859396            987.757568                  488.419933

In [11]:
converted_ampi = ampi_fixed.mul(gbp_usd, axis=0)

In [12]:
converted_ampi.head()

                AMPI UMV  Index (1000 in 1978)  Smoothed Index (0.2 alpha)
1977-12-01  1.809749e+07              0.000000                    0.000000
1978-01-01  1.931738e+07           1935.300000                    0.000000
1978-02-01  1.923144e+07           1926.690507                  387.920000
1978-03-01  1.916114e+07           1919.646935                  683.443494
1978-04-01  1.823692e+07           1827.055173                  903.430350

In [13]:
converted_ampi.to_csv("AMPI USD Converted.csv")